import { useMemo, useSyncExternalStore } from 'react'
import { cn } from '@/lib/utils'
import { resolveTokenColours } from '@/stencils/thumbnail'

/** The theme on <html data-theme>, updated when it changes. */
function subscribeTheme(onChange: () => void) {
  const observer = new MutationObserver(onChange)
  observer.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] })
  return () => observer.disconnect()
}
export const useThemeName = () => useSyncExternalStore(subscribeTheme, () => document.documentElement.dataset.theme ?? '')

/**
 * A stencil or template preview. The SVG is generated by thumbnail.ts from
 * validated data (no labels, colours checked by the schema), never taken from
 * a file, so it is safe to inline. Its var(--cl-…) colours are resolved to the
 * current theme's values here, so they work in every browser and follow theme
 * changes.
 */
export function Thumbnail({ svg, className }: { svg: string; className?: string }) {
  const theme = useThemeName()
  const html = useMemo(() => {
    const style = getComputedStyle(document.documentElement)
    return resolveTokenColours(svg, (token) => style.getPropertyValue(`--cl-${token}`).trim())
    // `theme` is the dependency that matters: new colours when it changes.
  }, [svg, theme])
  return (
    <span
      aria-hidden="true"
      className={cn('pointer-events-none block shrink-0 overflow-hidden rounded-sm border border-border bg-canvas p-1 [&>svg]:block [&>svg]:size-full', className)}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
